### ISSUE TITLE
Using ModuleBuilder.forModule('app') on a module which uses $location breaks the tests

### ISSUE THREAD

**Issue by tony-stark-eth** [evangalen/ng-improved-testing#11]
See there http://blog.programmingisart.com/angular-web-console-hacking-part-1-services/ fir $location troubleshooting.

My tests always will fail with Unknown provider: $rootElementProvider <- $rootElement <- $location <- $urlRouter <- $state because I am using the ui-router which is based on the $location service.

I hope you will fix it soon because your ngImprovedTesting is really great!

My test actually is:

``` javascript
describe('ngImprovedTesting mocked style MainController specification', function() {
    'use strict';

    beforeEach(
        ModuleBuilder.forModule('app')
            .controllerWithMocksFor('MainController', 'RobinsonApi')
            .build());

    describe('$scope', function() {

        var $scope;

        beforeEach(angular.mock.inject(function($rootScope, $controller) {
            $scope = $rootScope.$new();

            $controller('MainController', {$scope: $scope});
        }));

        describe('loadLanguages should fill languages', function() {
            it('should have language filled', inject(function(RobinsonApiMock) {
                dump(RobinsonApiMock);
            }));
        });
    });
});
```

**Comment by evangalen** [comment]
Just released 0.3.0-beta.3 that removes the 'strict mode' from the ModuleBuilder.
Therefor I also removed "includeAll()" (everything is now always included) and removed all of the "...AsIs" methods (i.e. "serviceAsIs").

I hope that 0.3.0-beta.3 will bring back you initial enthusiasm about "ngImprovedTesting" ;-)

For the final release of 0.3.0 I'm planning to also add support for mocking filters.
And for 0.4.0 I'm currently planning to add a controller test-fixture to ease the testing of AngularJS controllers.
